apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bs-hello-java
  name: bs-hello-java
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
  selector:
    app: bs-hello-java
status:
  loadBalancer: {}
